"""add production_brief to purchase orders

Revision ID: 7ed26197f8a6
Revises: 71605574e09c
Create Date: 2026-09-16 14:56:40.314993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed26197f8a6'
down_revision: Union[str, Sequence[str], None] = '71605574e09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('production_brief', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'production_brief')
    # ### end Alembic commands ###
