"""create initial schema

Revision ID: bedf3037f156
Revises: 
Create Date: 2026-08-15 17:39:20.825718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedf3037f156'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_brands_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_brands_slug_not_empty')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_brands_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('name', name=op.f('uq_brands_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_brands_slug'))
    )
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('decision_summary', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision_summary <> ''", name=op.f('ck_decisions_summary_not_empty')),
    sa.CheckConstraint("status IN ('proposed', 'approved', 'in_effect', 'superseded', 'archived')", name=op.f('ck_decisions_status_valid')),
    sa.CheckConstraint("title <> ''", name=op.f('ck_decisions_title_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index(op.f('ix_decisions_decided_at'), 'decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_decisions_status'), 'decisions', ['status'], unique=False)
    op.create_table('initiative_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_initiative_types_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_initiative_types_slug_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initiative_types')),
    sa.UniqueConstraint('name', name=op.f('uq_initiative_types_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_initiative_types_slug'))
    )
    op.create_index(op.f('ix_initiative_types_is_active'), 'initiative_types', ['is_active'], unique=False)
    op.create_table('inventory_location_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_inventory_location_types_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_inventory_location_types_slug_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_location_types')),
    sa.UniqueConstraint('name', name=op.f('uq_inventory_location_types_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_inventory_location_types_slug'))
    )
    op.create_index(op.f('ix_inventory_location_types_is_active'), 'inventory_location_types', ['is_active'], unique=False)
    op.create_table('inventory_movement_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_inventory_movement_types_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_inventory_movement_types_slug_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movement_types')),
    sa.UniqueConstraint('name', name=op.f('uq_inventory_movement_types_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_inventory_movement_types_slug'))
    )
    op.create_index(op.f('ix_inventory_movement_types_is_active'), 'inventory_movement_types', ['is_active'], unique=False)
    op.create_table('item_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_item_types_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_item_types_slug_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_types')),
    sa.UniqueConstraint('name', name=op.f('uq_item_types_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_item_types_slug'))
    )
    op.create_index(op.f('ix_item_types_is_active'), 'item_types', ['is_active'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("details <> ''", name=op.f('ck_observations_details_not_empty')),
    sa.CheckConstraint("title <> ''", name=op.f('ck_observations_title_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    op.create_index(op.f('ix_observations_observed_at'), 'observations', ['observed_at'], unique=False)
    op.create_table('partner_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_partner_types_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_partner_types_slug_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_types')),
    sa.UniqueConstraint('name', name=op.f('uq_partner_types_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_partner_types_slug'))
    )
    op.create_index(op.f('ix_partner_types_is_active'), 'partner_types', ['is_active'], unique=False)
    op.create_table('sourcing_trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_sourcing_trips_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_sourcing_trips_slug_not_empty')),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'completed', 'cancelled')", name=op.f('ck_sourcing_trips_status_valid')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_sourcing_trips_dates_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sourcing_trips')),
    sa.UniqueConstraint('slug', name=op.f('uq_sourcing_trips_slug'))
    )
    op.create_index(op.f('ix_sourcing_trips_start_date'), 'sourcing_trips', ['start_date'], unique=False)
    op.create_index(op.f('ix_sourcing_trips_status'), 'sourcing_trips', ['status'], unique=False)
    op.create_table('units_of_measure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_units_of_measure_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_units_of_measure_slug_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units_of_measure')),
    sa.UniqueConstraint('name', name=op.f('uq_units_of_measure_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_units_of_measure_slug'))
    )
    op.create_index(op.f('ix_units_of_measure_is_active'), 'units_of_measure', ['is_active'], unique=False)
    op.create_table('brand_decisions',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_decisions_brand_id_brands')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_brand_decisions_decision_id_decisions')),
    sa.PrimaryKeyConstraint('brand_id', 'decision_id', name=op.f('pk_brand_decisions'))
    )
    op.create_index(op.f('ix_brand_decisions_decision_id'), 'brand_decisions', ['decision_id'], unique=False)
    op.create_table('brand_observations',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_observations_brand_id_brands')),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_brand_observations_observation_id_observations')),
    sa.PrimaryKeyConstraint('brand_id', 'observation_id', name=op.f('pk_brand_observations'))
    )
    op.create_index(op.f('ix_brand_observations_observation_id'), 'brand_observations', ['observation_id'], unique=False)
    op.create_table('brand_sourcing_trips',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('sourcing_trip_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_sourcing_trips_brand_id_brands')),
    sa.ForeignKeyConstraint(['sourcing_trip_id'], ['sourcing_trips.id'], name=op.f('fk_brand_sourcing_trips_sourcing_trip_id_sourcing_trips')),
    sa.PrimaryKeyConstraint('brand_id', 'sourcing_trip_id', name=op.f('pk_brand_sourcing_trips'))
    )
    op.create_index(op.f('ix_brand_sourcing_trips_sourcing_trip_id'), 'brand_sourcing_trips', ['sourcing_trip_id'], unique=False)
    op.create_table('initiatives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('initiative_type_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_initiatives_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_initiatives_slug_not_empty')),
    sa.CheckConstraint("status IN ('planned', 'active', 'on_hold', 'completed', 'cancelled')", name=op.f('ck_initiatives_status_valid')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_initiatives_dates_ordered')),
    sa.ForeignKeyConstraint(['initiative_type_id'], ['initiative_types.id'], name=op.f('fk_initiatives_initiative_type_id_initiative_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initiatives')),
    sa.UniqueConstraint('slug', name=op.f('uq_initiatives_slug'))
    )
    op.create_index(op.f('ix_initiatives_initiative_type_id'), 'initiatives', ['initiative_type_id'], unique=False)
    op.create_index(op.f('ix_initiatives_start_date'), 'initiatives', ['start_date'], unique=False)
    op.create_index(op.f('ix_initiatives_status'), 'initiatives', ['status'], unique=False)
    op.create_table('inventory_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inventory_location_type_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.CHAR(length=2), nullable=True),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country_code ~ '^[A-Z]{2}$'", name=op.f('ck_inventory_locations_country_code_valid')),
    sa.CheckConstraint("name <> ''", name=op.f('ck_inventory_locations_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_inventory_locations_slug_not_empty')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_inventory_locations_status_valid')),
    sa.CheckConstraint('active_until >= active_from', name=op.f('ck_inventory_locations_active_dates_ordered')),
    sa.ForeignKeyConstraint(['inventory_location_type_id'], ['inventory_location_types.id'], name=op.f('fk_inventory_locations_inventory_location_type_id_inventory_location_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_locations')),
    sa.UniqueConstraint('slug', name=op.f('uq_inventory_locations_slug'))
    )
    op.create_index(op.f('ix_inventory_locations_city'), 'inventory_locations', ['city'], unique=False)
    op.create_index(op.f('ix_inventory_locations_country_code'), 'inventory_locations', ['country_code'], unique=False)
    op.create_index(op.f('ix_inventory_locations_inventory_location_type_id'), 'inventory_locations', ['inventory_location_type_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_status'), 'inventory_locations', ['status'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('item_type_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_items_name_not_empty')),
    sa.CheckConstraint("sku <> ''", name=op.f('ck_items_sku_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_items_slug_not_empty')),
    sa.CheckConstraint("status IN ('active', 'inactive', 'discontinued')", name=op.f('ck_items_status_valid')),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'], name=op.f('fk_items_item_type_id_item_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('sku', name=op.f('uq_items_sku')),
    sa.UniqueConstraint('slug', name=op.f('uq_items_slug'))
    )
    op.create_index(op.f('ix_items_item_type_id'), 'items', ['item_type_id'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_table('observation_decisions',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_observation_decisions_decision_id_decisions')),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_observation_decisions_observation_id_observations')),
    sa.PrimaryKeyConstraint('observation_id', 'decision_id', name=op.f('pk_observation_decisions'))
    )
    op.create_index(op.f('ix_observation_decisions_decision_id'), 'observation_decisions', ['decision_id'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('partner_type_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("name <> ''", name=op.f('ck_partners_name_not_empty')),
    sa.CheckConstraint("slug <> ''", name=op.f('ck_partners_slug_not_empty')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_partners_status_valid')),
    sa.ForeignKeyConstraint(['partner_type_id'], ['partner_types.id'], name=op.f('fk_partners_partner_type_id_partner_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners')),
    sa.UniqueConstraint('slug', name=op.f('uq_partners_slug'))
    )
    op.create_index(op.f('ix_partners_partner_type_id'), 'partners', ['partner_type_id'], unique=False)
    op.create_index(op.f('ix_partners_status'), 'partners', ['status'], unique=False)
    op.create_table('sourcing_trip_decisions',
    sa.Column('sourcing_trip_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_sourcing_trip_decisions_decision_id_decisions')),
    sa.ForeignKeyConstraint(['sourcing_trip_id'], ['sourcing_trips.id'], name=op.f('fk_sourcing_trip_decisions_sourcing_trip_id_sourcing_trips')),
    sa.PrimaryKeyConstraint('sourcing_trip_id', 'decision_id', name=op.f('pk_sourcing_trip_decisions'))
    )
    op.create_index(op.f('ix_sourcing_trip_decisions_decision_id'), 'sourcing_trip_decisions', ['decision_id'], unique=False)
    op.create_table('sourcing_trip_observations',
    sa.Column('sourcing_trip_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_sourcing_trip_observations_observation_id_observations')),
    sa.ForeignKeyConstraint(['sourcing_trip_id'], ['sourcing_trips.id'], name=op.f('fk_sourcing_trip_observations_sourcing_trip_id_sourcing_trips')),
    sa.PrimaryKeyConstraint('sourcing_trip_id', 'observation_id', name=op.f('pk_sourcing_trip_observations'))
    )
    op.create_index(op.f('ix_sourcing_trip_observations_observation_id'), 'sourcing_trip_observations', ['observation_id'], unique=False)
    op.create_table('brand_initiatives',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_initiatives_brand_id_brands')),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], name=op.f('fk_brand_initiatives_initiative_id_initiatives')),
    sa.PrimaryKeyConstraint('brand_id', 'initiative_id', name=op.f('pk_brand_initiatives'))
    )
    op.create_index(op.f('ix_brand_initiatives_initiative_id'), 'brand_initiatives', ['initiative_id'], unique=False)
    op.create_table('brand_inventory_locations',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_inventory_locations_brand_id_brands')),
    sa.ForeignKeyConstraint(['inventory_location_id'], ['inventory_locations.id'], name=op.f('fk_brand_inventory_locations_inventory_location_id_inventory_locations')),
    sa.PrimaryKeyConstraint('brand_id', 'inventory_location_id', name=op.f('pk_brand_inventory_locations'))
    )
    op.create_index(op.f('ix_brand_inventory_locations_inventory_location_id'), 'brand_inventory_locations', ['inventory_location_id'], unique=False)
    op.create_table('brand_items',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_items_brand_id_brands')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_brand_items_item_id_items')),
    sa.PrimaryKeyConstraint('brand_id', 'item_id', name=op.f('pk_brand_items'))
    )
    op.create_index(op.f('ix_brand_items_item_id'), 'brand_items', ['item_id'], unique=False)
    op.create_table('brand_partners',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_partners_brand_id_brands')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_brand_partners_partner_id_partners')),
    sa.PrimaryKeyConstraint('brand_id', 'partner_id', name=op.f('pk_brand_partners'))
    )
    op.create_index(op.f('ix_brand_partners_partner_id'), 'brand_partners', ['partner_id'], unique=False)
    op.create_table('decision_inventory_locations',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_inventory_locations_decision_id_decisions')),
    sa.ForeignKeyConstraint(['inventory_location_id'], ['inventory_locations.id'], name=op.f('fk_decision_inventory_locations_inventory_location_id_inventory_locations')),
    sa.PrimaryKeyConstraint('decision_id', 'inventory_location_id', name=op.f('pk_decision_inventory_locations'))
    )
    op.create_index(op.f('ix_decision_inventory_locations_inventory_location_id'), 'decision_inventory_locations', ['inventory_location_id'], unique=False)
    op.create_table('decision_items',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_items_decision_id_decisions')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_decision_items_item_id_items')),
    sa.PrimaryKeyConstraint('decision_id', 'item_id', name=op.f('pk_decision_items'))
    )
    op.create_index(op.f('ix_decision_items_item_id'), 'decision_items', ['item_id'], unique=False)
    op.create_table('decision_partners',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_partners_decision_id_decisions')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_decision_partners_partner_id_partners')),
    sa.PrimaryKeyConstraint('decision_id', 'partner_id', name=op.f('pk_decision_partners'))
    )
    op.create_index(op.f('ix_decision_partners_partner_id'), 'decision_partners', ['partner_id'], unique=False)
    op.create_table('inbound_shipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbound_shipment_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('carrier_name', sa.String(length=100), nullable=True),
    sa.Column('destination_inventory_location_id', sa.Uuid(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("inbound_shipment_number <> ''", name=op.f('ck_inbound_shipments_number_not_empty')),
    sa.CheckConstraint("status IN ('preparing', 'in_transit', 'partially_received', 'received', 'closed')", name=op.f('ck_inbound_shipments_status_valid')),
    sa.CheckConstraint('received_at >= shipped_at', name=op.f('ck_inbound_shipments_dates_ordered')),
    sa.ForeignKeyConstraint(['destination_inventory_location_id'], ['inventory_locations.id'], name=op.f('fk_inbound_shipments_destination_inventory_location_id_inventory_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_shipments')),
    sa.UniqueConstraint('inbound_shipment_number', name=op.f('uq_inbound_shipments_inbound_shipment_number'))
    )
    op.create_index(op.f('ix_inbound_shipments_destination_inventory_location_id'), 'inbound_shipments', ['destination_inventory_location_id'], unique=False)
    op.create_index(op.f('ix_inbound_shipments_received_at'), 'inbound_shipments', ['received_at'], unique=False)
    op.create_index(op.f('ix_inbound_shipments_shipped_at'), 'inbound_shipments', ['shipped_at'], unique=False)
    op.create_index(op.f('ix_inbound_shipments_status'), 'inbound_shipments', ['status'], unique=False)
    op.create_table('initiative_decisions',
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_initiative_decisions_decision_id_decisions')),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], name=op.f('fk_initiative_decisions_initiative_id_initiatives')),
    sa.PrimaryKeyConstraint('initiative_id', 'decision_id', name=op.f('pk_initiative_decisions'))
    )
    op.create_index(op.f('ix_initiative_decisions_decision_id'), 'initiative_decisions', ['decision_id'], unique=False)
    op.create_table('initiative_inventory_locations',
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], name=op.f('fk_initiative_inventory_locations_initiative_id_initiatives')),
    sa.ForeignKeyConstraint(['inventory_location_id'], ['inventory_locations.id'], name=op.f('fk_initiative_inventory_locations_inventory_location_id_inventory_locations')),
    sa.PrimaryKeyConstraint('initiative_id', 'inventory_location_id', name=op.f('pk_initiative_inventory_locations'))
    )
    op.create_index(op.f('ix_initiative_inventory_locations_inventory_location_id'), 'initiative_inventory_locations', ['inventory_location_id'], unique=False)
    op.create_table('initiative_items',
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], name=op.f('fk_initiative_items_initiative_id_initiatives')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_initiative_items_item_id_items')),
    sa.PrimaryKeyConstraint('initiative_id', 'item_id', name=op.f('pk_initiative_items'))
    )
    op.create_index(op.f('ix_initiative_items_item_id'), 'initiative_items', ['item_id'], unique=False)
    op.create_table('initiative_observations',
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], name=op.f('fk_initiative_observations_initiative_id_initiatives')),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_initiative_observations_observation_id_observations')),
    sa.PrimaryKeyConstraint('initiative_id', 'observation_id', name=op.f('pk_initiative_observations'))
    )
    op.create_index(op.f('ix_initiative_observations_observation_id'), 'initiative_observations', ['observation_id'], unique=False)
    op.create_table('initiative_partners',
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], name=op.f('fk_initiative_partners_initiative_id_initiatives')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_initiative_partners_partner_id_partners')),
    sa.PrimaryKeyConstraint('initiative_id', 'partner_id', name=op.f('pk_initiative_partners'))
    )
    op.create_index(op.f('ix_initiative_partners_partner_id'), 'initiative_partners', ['partner_id'], unique=False)
    op.create_table('initiative_sourcing_trips',
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('sourcing_trip_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], name=op.f('fk_initiative_sourcing_trips_initiative_id_initiatives')),
    sa.ForeignKeyConstraint(['sourcing_trip_id'], ['sourcing_trips.id'], name=op.f('fk_initiative_sourcing_trips_sourcing_trip_id_sourcing_trips')),
    sa.PrimaryKeyConstraint('initiative_id', 'sourcing_trip_id', name=op.f('pk_initiative_sourcing_trips'))
    )
    op.create_index(op.f('ix_initiative_sourcing_trips_sourcing_trip_id'), 'initiative_sourcing_trips', ['sourcing_trip_id'], unique=False)
    op.create_table('inventory_balances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_location_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_of_measure_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name=op.f('ck_inventory_balances_quantity_on_hand_non_negative')),
    sa.ForeignKeyConstraint(['inventory_location_id'], ['inventory_locations.id'], name=op.f('fk_inventory_balances_inventory_location_id_inventory_locations')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_inventory_balances_item_id_items')),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.id'], name=op.f('fk_inventory_balances_unit_of_measure_id_units_of_measure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_balances')),
    sa.UniqueConstraint('item_id', 'inventory_location_id', name='item_location_unique')
    )
    op.create_index(op.f('ix_inventory_balances_inventory_location_id'), 'inventory_balances', ['inventory_location_id'], unique=False)
    op.create_index(op.f('ix_inventory_balances_item_id'), 'inventory_balances', ['item_id'], unique=False)
    op.create_table('item_partners',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_partners_item_id_items')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_item_partners_partner_id_partners')),
    sa.PrimaryKeyConstraint('item_id', 'partner_id', name=op.f('pk_item_partners'))
    )
    op.create_index(op.f('ix_item_partners_partner_id'), 'item_partners', ['partner_id'], unique=False)
    op.create_table('observation_inventory_locations',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_location_id'], ['inventory_locations.id'], name=op.f('fk_observation_inventory_locations_inventory_location_id_inventory_locations')),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_observation_inventory_locations_observation_id_observations')),
    sa.PrimaryKeyConstraint('observation_id', 'inventory_location_id', name=op.f('pk_observation_inventory_locations'))
    )
    op.create_index(op.f('ix_observation_inventory_locations_inventory_location_id'), 'observation_inventory_locations', ['inventory_location_id'], unique=False)
    op.create_table('observation_items',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_observation_items_item_id_items')),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_observation_items_observation_id_observations')),
    sa.PrimaryKeyConstraint('observation_id', 'item_id', name=op.f('pk_observation_items'))
    )
    op.create_index(op.f('ix_observation_items_item_id'), 'observation_items', ['item_id'], unique=False)
    op.create_table('observation_partners',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_observation_partners_observation_id_observations')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_observation_partners_partner_id_partners')),
    sa.PrimaryKeyConstraint('observation_id', 'partner_id', name=op.f('pk_observation_partners'))
    )
    op.create_index(op.f('ix_observation_partners_partner_id'), 'observation_partners', ['partner_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=50), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency_code ~ '^[A-Z]{3}$'", name=op.f('ck_purchase_orders_currency_code_valid')),
    sa.CheckConstraint("purchase_order_number <> ''", name=op.f('ck_purchase_orders_number_not_empty')),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'accepted', 'in_production', 'partially_fulfilled', 'fulfilled', 'cancelled')", name=op.f('ck_purchase_orders_status_valid')),
    sa.CheckConstraint('expected_date >= order_date', name=op.f('ck_purchase_orders_dates_ordered')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_purchase_orders_partner_id_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('purchase_order_number', name=op.f('uq_purchase_orders_purchase_order_number'))
    )
    op.create_index(op.f('ix_purchase_orders_order_date'), 'purchase_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_partner_id'), 'purchase_orders', ['partner_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_table('sourcing_trip_items',
    sa.Column('sourcing_trip_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_sourcing_trip_items_item_id_items')),
    sa.ForeignKeyConstraint(['sourcing_trip_id'], ['sourcing_trips.id'], name=op.f('fk_sourcing_trip_items_sourcing_trip_id_sourcing_trips')),
    sa.PrimaryKeyConstraint('sourcing_trip_id', 'item_id', name=op.f('pk_sourcing_trip_items'))
    )
    op.create_index(op.f('ix_sourcing_trip_items_item_id'), 'sourcing_trip_items', ['item_id'], unique=False)
    op.create_table('sourcing_trip_partners',
    sa.Column('sourcing_trip_id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_sourcing_trip_partners_partner_id_partners')),
    sa.ForeignKeyConstraint(['sourcing_trip_id'], ['sourcing_trips.id'], name=op.f('fk_sourcing_trip_partners_sourcing_trip_id_sourcing_trips')),
    sa.PrimaryKeyConstraint('sourcing_trip_id', 'partner_id', name=op.f('pk_sourcing_trip_partners'))
    )
    op.create_index(op.f('ix_sourcing_trip_partners_partner_id'), 'sourcing_trip_partners', ['partner_id'], unique=False)
    op.create_table('brand_inbound_shipments',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('inbound_shipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_inbound_shipments_brand_id_brands')),
    sa.ForeignKeyConstraint(['inbound_shipment_id'], ['inbound_shipments.id'], name=op.f('fk_brand_inbound_shipments_inbound_shipment_id_inbound_shipments')),
    sa.PrimaryKeyConstraint('brand_id', 'inbound_shipment_id', name=op.f('pk_brand_inbound_shipments'))
    )
    op.create_index(op.f('ix_brand_inbound_shipments_inbound_shipment_id'), 'brand_inbound_shipments', ['inbound_shipment_id'], unique=False)
    op.create_table('brand_purchase_orders',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_purchase_orders_brand_id_brands')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_brand_purchase_orders_purchase_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('brand_id', 'purchase_order_id', name=op.f('pk_brand_purchase_orders'))
    )
    op.create_index(op.f('ix_brand_purchase_orders_purchase_order_id'), 'brand_purchase_orders', ['purchase_order_id'], unique=False)
    op.create_table('decision_inbound_shipments',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('inbound_shipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_inbound_shipments_decision_id_decisions')),
    sa.ForeignKeyConstraint(['inbound_shipment_id'], ['inbound_shipments.id'], name=op.f('fk_decision_inbound_shipments_inbound_shipment_id_inbound_shipments')),
    sa.PrimaryKeyConstraint('decision_id', 'inbound_shipment_id', name=op.f('pk_decision_inbound_shipments'))
    )
    op.create_index(op.f('ix_decision_inbound_shipments_inbound_shipment_id'), 'decision_inbound_shipments', ['inbound_shipment_id'], unique=False)
    op.create_table('decision_purchase_orders',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_purchase_orders_decision_id_decisions')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_decision_purchase_orders_purchase_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('decision_id', 'purchase_order_id', name=op.f('pk_decision_purchase_orders'))
    )
    op.create_index(op.f('ix_decision_purchase_orders_purchase_order_id'), 'decision_purchase_orders', ['purchase_order_id'], unique=False)
    op.create_table('initiative_inbound_shipments',
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('inbound_shipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inbound_shipment_id'], ['inbound_shipments.id'], name=op.f('fk_initiative_inbound_shipments_inbound_shipment_id_inbound_shipments')),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], name=op.f('fk_initiative_inbound_shipments_initiative_id_initiatives')),
    sa.PrimaryKeyConstraint('initiative_id', 'inbound_shipment_id', name=op.f('pk_initiative_inbound_shipments'))
    )
    op.create_index(op.f('ix_initiative_inbound_shipments_inbound_shipment_id'), 'initiative_inbound_shipments', ['inbound_shipment_id'], unique=False)
    op.create_table('initiative_purchase_orders',
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], name=op.f('fk_initiative_purchase_orders_initiative_id_initiatives')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_initiative_purchase_orders_purchase_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('initiative_id', 'purchase_order_id', name=op.f('pk_initiative_purchase_orders'))
    )
    op.create_index(op.f('ix_initiative_purchase_orders_purchase_order_id'), 'initiative_purchase_orders', ['purchase_order_id'], unique=False)
    op.create_table('observation_inbound_shipments',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('inbound_shipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inbound_shipment_id'], ['inbound_shipments.id'], name=op.f('fk_observation_inbound_shipments_inbound_shipment_id_inbound_shipments')),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_observation_inbound_shipments_observation_id_observations')),
    sa.PrimaryKeyConstraint('observation_id', 'inbound_shipment_id', name=op.f('pk_observation_inbound_shipments'))
    )
    op.create_index(op.f('ix_observation_inbound_shipments_inbound_shipment_id'), 'observation_inbound_shipments', ['inbound_shipment_id'], unique=False)
    op.create_table('observation_purchase_orders',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_observation_purchase_orders_observation_id_observations')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_observation_purchase_orders_purchase_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('observation_id', 'purchase_order_id', name=op.f('pk_observation_purchase_orders'))
    )
    op.create_index(op.f('ix_observation_purchase_orders_purchase_order_id'), 'observation_purchase_orders', ['purchase_order_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity_ordered', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_of_measure_id', sa.Uuid(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('line_number > 0', name=op.f('ck_purchase_order_lines_line_number_positive')),
    sa.CheckConstraint('quantity_ordered >= 0', name=op.f('ck_purchase_order_lines_quantity_ordered_non_negative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_purchase_order_lines_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_purchase_order_lines_item_id_items')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_lines_purchase_order_id_purchase_orders')),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.id'], name=op.f('fk_purchase_order_lines_unit_of_measure_id_units_of_measure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_lines')),
    sa.UniqueConstraint('purchase_order_id', 'line_number', name='po_line_number_unique')
    )
    op.create_index(op.f('ix_purchase_order_lines_item_id'), 'purchase_order_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_table('sourcing_trip_inbound_shipments',
    sa.Column('sourcing_trip_id', sa.Uuid(), nullable=False),
    sa.Column('inbound_shipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inbound_shipment_id'], ['inbound_shipments.id'], name=op.f('fk_sourcing_trip_inbound_shipments_inbound_shipment_id_inbound_shipments')),
    sa.ForeignKeyConstraint(['sourcing_trip_id'], ['sourcing_trips.id'], name=op.f('fk_sourcing_trip_inbound_shipments_sourcing_trip_id_sourcing_trips')),
    sa.PrimaryKeyConstraint('sourcing_trip_id', 'inbound_shipment_id', name=op.f('pk_sourcing_trip_inbound_shipments'))
    )
    op.create_index(op.f('ix_sourcing_trip_inbound_shipments_inbound_shipment_id'), 'sourcing_trip_inbound_shipments', ['inbound_shipment_id'], unique=False)
    op.create_table('sourcing_trip_purchase_orders',
    sa.Column('sourcing_trip_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_sourcing_trip_purchase_orders_purchase_order_id_purchase_orders')),
    sa.ForeignKeyConstraint(['sourcing_trip_id'], ['sourcing_trips.id'], name=op.f('fk_sourcing_trip_purchase_orders_sourcing_trip_id_sourcing_trips')),
    sa.PrimaryKeyConstraint('sourcing_trip_id', 'purchase_order_id', name=op.f('pk_sourcing_trip_purchase_orders'))
    )
    op.create_index(op.f('ix_sourcing_trip_purchase_orders_purchase_order_id'), 'sourcing_trip_purchase_orders', ['purchase_order_id'], unique=False)
    op.create_table('inbound_shipment_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbound_shipment_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_shipped', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('quantity_accepted', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('quantity_damaged', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_of_measure_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_accepted >= 0', name=op.f('ck_inbound_shipment_lines_quantity_accepted_non_negative')),
    sa.CheckConstraint('quantity_damaged >= 0', name=op.f('ck_inbound_shipment_lines_quantity_damaged_non_negative')),
    sa.CheckConstraint('quantity_received >= 0', name=op.f('ck_inbound_shipment_lines_quantity_received_non_negative')),
    sa.CheckConstraint('quantity_shipped >= 0', name=op.f('ck_inbound_shipment_lines_quantity_shipped_non_negative')),
    sa.ForeignKeyConstraint(['inbound_shipment_id'], ['inbound_shipments.id'], name=op.f('fk_inbound_shipment_lines_inbound_shipment_id_inbound_shipments')),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], name=op.f('fk_inbound_shipment_lines_purchase_order_line_id_purchase_order_lines')),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.id'], name=op.f('fk_inbound_shipment_lines_unit_of_measure_id_units_of_measure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_shipment_lines')),
    sa.UniqueConstraint('inbound_shipment_id', 'purchase_order_line_id', name='shipment_po_line_unique')
    )
    op.create_index(op.f('ix_inbound_shipment_lines_inbound_shipment_id'), 'inbound_shipment_lines', ['inbound_shipment_id'], unique=False)
    op.create_index(op.f('ix_inbound_shipment_lines_purchase_order_line_id'), 'inbound_shipment_lines', ['purchase_order_line_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_location_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_movement_type_id', sa.Uuid(), nullable=False),
    sa.Column('inbound_shipment_line_id', sa.Uuid(), nullable=True),
    sa.Column('related_movement_id', sa.Uuid(), nullable=True),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_of_measure_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_delta <> 0', name=op.f('ck_inventory_movements_quantity_delta_non_zero')),
    sa.ForeignKeyConstraint(['inbound_shipment_line_id'], ['inbound_shipment_lines.id'], name=op.f('fk_inventory_movements_inbound_shipment_line_id_inbound_shipment_lines')),
    sa.ForeignKeyConstraint(['inventory_location_id'], ['inventory_locations.id'], name=op.f('fk_inventory_movements_inventory_location_id_inventory_locations')),
    sa.ForeignKeyConstraint(['inventory_movement_type_id'], ['inventory_movement_types.id'], name=op.f('fk_inventory_movements_inventory_movement_type_id_inventory_movement_types')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_inventory_movements_item_id_items')),
    sa.ForeignKeyConstraint(['related_movement_id'], ['inventory_movements.id'], name=op.f('fk_inventory_movements_related_movement_id_inventory_movements')),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.id'], name=op.f('fk_inventory_movements_unit_of_measure_id_units_of_measure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movements'))
    )
    op.create_index(op.f('ix_inventory_movements_inventory_location_id'), 'inventory_movements', ['inventory_location_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_inventory_movement_type_id'), 'inventory_movements', ['inventory_movement_type_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_item_id'), 'inventory_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_occurred_at'), 'inventory_movements', ['occurred_at'], unique=False)
    op.create_table('decision_inventory_movements',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_movement_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_inventory_movements_decision_id_decisions')),
    sa.ForeignKeyConstraint(['inventory_movement_id'], ['inventory_movements.id'], name=op.f('fk_decision_inventory_movements_inventory_movement_id_inventory_movements')),
    sa.PrimaryKeyConstraint('decision_id', 'inventory_movement_id', name=op.f('pk_decision_inventory_movements'))
    )
    op.create_index(op.f('ix_decision_inventory_movements_inventory_movement_id'), 'decision_inventory_movements', ['inventory_movement_id'], unique=False)
    op.create_table('observation_inventory_movements',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_movement_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_movement_id'], ['inventory_movements.id'], name=op.f('fk_observation_inventory_movements_inventory_movement_id_inventory_movements')),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_observation_inventory_movements_observation_id_observations')),
    sa.PrimaryKeyConstraint('observation_id', 'inventory_movement_id', name=op.f('pk_observation_inventory_movements'))
    )
    op.create_index(op.f('ix_observation_inventory_movements_inventory_movement_id'), 'observation_inventory_movements', ['inventory_movement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observation_inventory_movements_inventory_movement_id'), table_name='observation_inventory_movements')
    op.drop_table('observation_inventory_movements')
    op.drop_index(op.f('ix_decision_inventory_movements_inventory_movement_id'), table_name='decision_inventory_movements')
    op.drop_table('decision_inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_occurred_at'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_item_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_inventory_movement_type_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_inventory_location_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_inbound_shipment_lines_purchase_order_line_id'), table_name='inbound_shipment_lines')
    op.drop_index(op.f('ix_inbound_shipment_lines_inbound_shipment_id'), table_name='inbound_shipment_lines')
    op.drop_table('inbound_shipment_lines')
    op.drop_index(op.f('ix_sourcing_trip_purchase_orders_purchase_order_id'), table_name='sourcing_trip_purchase_orders')
    op.drop_table('sourcing_trip_purchase_orders')
    op.drop_index(op.f('ix_sourcing_trip_inbound_shipments_inbound_shipment_id'), table_name='sourcing_trip_inbound_shipments')
    op.drop_table('sourcing_trip_inbound_shipments')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_item_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_observation_purchase_orders_purchase_order_id'), table_name='observation_purchase_orders')
    op.drop_table('observation_purchase_orders')
    op.drop_index(op.f('ix_observation_inbound_shipments_inbound_shipment_id'), table_name='observation_inbound_shipments')
    op.drop_table('observation_inbound_shipments')
    op.drop_index(op.f('ix_initiative_purchase_orders_purchase_order_id'), table_name='initiative_purchase_orders')
    op.drop_table('initiative_purchase_orders')
    op.drop_index(op.f('ix_initiative_inbound_shipments_inbound_shipment_id'), table_name='initiative_inbound_shipments')
    op.drop_table('initiative_inbound_shipments')
    op.drop_index(op.f('ix_decision_purchase_orders_purchase_order_id'), table_name='decision_purchase_orders')
    op.drop_table('decision_purchase_orders')
    op.drop_index(op.f('ix_decision_inbound_shipments_inbound_shipment_id'), table_name='decision_inbound_shipments')
    op.drop_table('decision_inbound_shipments')
    op.drop_index(op.f('ix_brand_purchase_orders_purchase_order_id'), table_name='brand_purchase_orders')
    op.drop_table('brand_purchase_orders')
    op.drop_index(op.f('ix_brand_inbound_shipments_inbound_shipment_id'), table_name='brand_inbound_shipments')
    op.drop_table('brand_inbound_shipments')
    op.drop_index(op.f('ix_sourcing_trip_partners_partner_id'), table_name='sourcing_trip_partners')
    op.drop_table('sourcing_trip_partners')
    op.drop_index(op.f('ix_sourcing_trip_items_item_id'), table_name='sourcing_trip_items')
    op.drop_table('sourcing_trip_items')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_partner_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_order_date'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_observation_partners_partner_id'), table_name='observation_partners')
    op.drop_table('observation_partners')
    op.drop_index(op.f('ix_observation_items_item_id'), table_name='observation_items')
    op.drop_table('observation_items')
    op.drop_index(op.f('ix_observation_inventory_locations_inventory_location_id'), table_name='observation_inventory_locations')
    op.drop_table('observation_inventory_locations')
    op.drop_index(op.f('ix_item_partners_partner_id'), table_name='item_partners')
    op.drop_table('item_partners')
    op.drop_index(op.f('ix_inventory_balances_item_id'), table_name='inventory_balances')
    op.drop_index(op.f('ix_inventory_balances_inventory_location_id'), table_name='inventory_balances')
    op.drop_table('inventory_balances')
    op.drop_index(op.f('ix_initiative_sourcing_trips_sourcing_trip_id'), table_name='initiative_sourcing_trips')
    op.drop_table('initiative_sourcing_trips')
    op.drop_index(op.f('ix_initiative_partners_partner_id'), table_name='initiative_partners')
    op.drop_table('initiative_partners')
    op.drop_index(op.f('ix_initiative_observations_observation_id'), table_name='initiative_observations')
    op.drop_table('initiative_observations')
    op.drop_index(op.f('ix_initiative_items_item_id'), table_name='initiative_items')
    op.drop_table('initiative_items')
    op.drop_index(op.f('ix_initiative_inventory_locations_inventory_location_id'), table_name='initiative_inventory_locations')
    op.drop_table('initiative_inventory_locations')
    op.drop_index(op.f('ix_initiative_decisions_decision_id'), table_name='initiative_decisions')
    op.drop_table('initiative_decisions')
    op.drop_index(op.f('ix_inbound_shipments_status'), table_name='inbound_shipments')
    op.drop_index(op.f('ix_inbound_shipments_shipped_at'), table_name='inbound_shipments')
    op.drop_index(op.f('ix_inbound_shipments_received_at'), table_name='inbound_shipments')
    op.drop_index(op.f('ix_inbound_shipments_destination_inventory_location_id'), table_name='inbound_shipments')
    op.drop_table('inbound_shipments')
    op.drop_index(op.f('ix_decision_partners_partner_id'), table_name='decision_partners')
    op.drop_table('decision_partners')
    op.drop_index(op.f('ix_decision_items_item_id'), table_name='decision_items')
    op.drop_table('decision_items')
    op.drop_index(op.f('ix_decision_inventory_locations_inventory_location_id'), table_name='decision_inventory_locations')
    op.drop_table('decision_inventory_locations')
    op.drop_index(op.f('ix_brand_partners_partner_id'), table_name='brand_partners')
    op.drop_table('brand_partners')
    op.drop_index(op.f('ix_brand_items_item_id'), table_name='brand_items')
    op.drop_table('brand_items')
    op.drop_index(op.f('ix_brand_inventory_locations_inventory_location_id'), table_name='brand_inventory_locations')
    op.drop_table('brand_inventory_locations')
    op.drop_index(op.f('ix_brand_initiatives_initiative_id'), table_name='brand_initiatives')
    op.drop_table('brand_initiatives')
    op.drop_index(op.f('ix_sourcing_trip_observations_observation_id'), table_name='sourcing_trip_observations')
    op.drop_table('sourcing_trip_observations')
    op.drop_index(op.f('ix_sourcing_trip_decisions_decision_id'), table_name='sourcing_trip_decisions')
    op.drop_table('sourcing_trip_decisions')
    op.drop_index(op.f('ix_partners_status'), table_name='partners')
    op.drop_index(op.f('ix_partners_partner_type_id'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_observation_decisions_decision_id'), table_name='observation_decisions')
    op.drop_table('observation_decisions')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_item_type_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_inventory_locations_status'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_inventory_location_type_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_country_code'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_city'), table_name='inventory_locations')
    op.drop_table('inventory_locations')
    op.drop_index(op.f('ix_initiatives_status'), table_name='initiatives')
    op.drop_index(op.f('ix_initiatives_start_date'), table_name='initiatives')
    op.drop_index(op.f('ix_initiatives_initiative_type_id'), table_name='initiatives')
    op.drop_table('initiatives')
    op.drop_index(op.f('ix_brand_sourcing_trips_sourcing_trip_id'), table_name='brand_sourcing_trips')
    op.drop_table('brand_sourcing_trips')
    op.drop_index(op.f('ix_brand_observations_observation_id'), table_name='brand_observations')
    op.drop_table('brand_observations')
    op.drop_index(op.f('ix_brand_decisions_decision_id'), table_name='brand_decisions')
    op.drop_table('brand_decisions')
    op.drop_index(op.f('ix_units_of_measure_is_active'), table_name='units_of_measure')
    op.drop_table('units_of_measure')
    op.drop_index(op.f('ix_sourcing_trips_status'), table_name='sourcing_trips')
    op.drop_index(op.f('ix_sourcing_trips_start_date'), table_name='sourcing_trips')
    op.drop_table('sourcing_trips')
    op.drop_index(op.f('ix_partner_types_is_active'), table_name='partner_types')
    op.drop_table('partner_types')
    op.drop_index(op.f('ix_observations_observed_at'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_item_types_is_active'), table_name='item_types')
    op.drop_table('item_types')
    op.drop_index(op.f('ix_inventory_movement_types_is_active'), table_name='inventory_movement_types')
    op.drop_table('inventory_movement_types')
    op.drop_index(op.f('ix_inventory_location_types_is_active'), table_name='inventory_location_types')
    op.drop_table('inventory_location_types')
    op.drop_index(op.f('ix_initiative_types_is_active'), table_name='initiative_types')
    op.drop_table('initiative_types')
    op.drop_index(op.f('ix_decisions_status'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decided_at'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('brands')
    # ### end Alembic commands ###
